version: '3.8'
services:
  backend_test:
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             pytest"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.test
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: test_db
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_HOST: db
      SQL_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
