name: Check Docker Build

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  docker_build_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Docker Buildx (opcional pero recomendado)
        uses: docker/setup-buildx-action@v3

      - name: Validate Docker Compose build
        run: |
          docker-compose -f docker-compose.yml build