name: Run Pytest with Docker

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Build and run tests with Docker
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from backend_test
