name: Continuous Integration

on:
  pull_request:
    branches:
      - '**'

jobs:
  black:
    uses: ./.github/workflows/_black.yml
    with:
      ref: ${{ github.ref }}

  prettier:
    uses: ./.github/workflows/_prettier.yml
    with:
      ref: ${{ github.ref }}

  test:
    uses: ./.github/workflows/_pytest.yml
    with:
      ref: ${{ github.ref }}

  docker_build:
    uses: ./.github/workflows/_docker-build-check.yml
    with:
      ref: ${{ github.ref }}
